repos:
-   repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
    - id: black
      stages: [push]
      language_version: python3.6
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.1.0
    hooks:
    -   id: pylint
        stages: [push]
-   repo: local
    hooks:
    -   id: pytest
        stages: [push]
        name: pytest
        entry: .venv/bin/pytest
        language: script
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true
